// <auto-generated />
using System;
using ConferenceBooking.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ConferenceBooking.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260901115105_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ConferenceBooking.Api.Domain.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HallCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("HallId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ServicesCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HallId", "StartsAt", "EndsAt");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("ConferenceBooking.Api.Domain.Hall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("BasePricePerHour")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted");

                    b.ToTable("Halls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BasePricePerHour = 2000m,
                            Capacity = 50,
                            IsDeleted = false,
                            Name = "Зал A"
                        },
                        new
                        {
                            Id = 2,
                            BasePricePerHour = 3500m,
                            Capacity = 100,
                            IsDeleted = false,
                            Name = "Зал B"
                        },
                        new
                        {
                            Id = 3,
                            BasePricePerHour = 1500m,
                            Capacity = 30,
                            IsDeleted = false,
                            Name = "Зал C"
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Api.Domain.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BookingId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerBooking")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Проектор",
                            PricePerBooking = 500m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wi-Fi",
                            PricePerBooking = 300m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Звук",
                            PricePerBooking = 700m
                        });
                });

            modelBuilder.Entity("HallService", b =>
                {
                    b.Property<int>("AvailableServicesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HallsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AvailableServicesId", "HallsId");

                    b.HasIndex("HallsId");

                    b.ToTable("HallService");

                    b.HasData(
                        new
                        {
                            AvailableServicesId = 1,
                            HallsId = 1
                        },
                        new
                        {
                            AvailableServicesId = 2,
                            HallsId = 1
                        },
                        new
                        {
                            AvailableServicesId = 3,
                            HallsId = 1
                        },
                        new
                        {
                            AvailableServicesId = 1,
                            HallsId = 2
                        },
                        new
                        {
                            AvailableServicesId = 2,
                            HallsId = 2
                        },
                        new
                        {
                            AvailableServicesId = 3,
                            HallsId = 2
                        },
                        new
                        {
                            AvailableServicesId = 1,
                            HallsId = 3
                        },
                        new
                        {
                            AvailableServicesId = 2,
                            HallsId = 3
                        },
                        new
                        {
                            AvailableServicesId = 3,
                            HallsId = 3
                        });
                });

            modelBuilder.Entity("ConferenceBooking.Api.Domain.Booking", b =>
                {
                    b.HasOne("ConferenceBooking.Api.Domain.Hall", "Hall")
                        .WithMany("Bookings")
                        .HasForeignKey("HallId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Hall");
                });

            modelBuilder.Entity("ConferenceBooking.Api.Domain.Service", b =>
                {
                    b.HasOne("ConferenceBooking.Api.Domain.Booking", null)
                        .WithMany("Services")
                        .HasForeignKey("BookingId");
                });

            modelBuilder.Entity("HallService", b =>
                {
                    b.HasOne("ConferenceBooking.Api.Domain.Service", null)
                        .WithMany()
                        .HasForeignKey("AvailableServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ConferenceBooking.Api.Domain.Hall", null)
                        .WithMany()
                        .HasForeignKey("HallsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ConferenceBooking.Api.Domain.Booking", b =>
                {
                    b.Navigation("Services");
                });

            modelBuilder.Entity("ConferenceBooking.Api.Domain.Hall", b =>
                {
                    b.Navigation("Bookings");
                });
#pragma warning restore 612, 618
        }
    }
}
